services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: caio
      POSTGRES_DB: database
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend-kotlin/
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
