version: '3.9'

services:

  db:
    image: postgres

    environment:
      POSTGRES_PASSWORD: caio
      POSTGRES_DB: database

    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/

    ports:
      - "5432:5432"